baseurl = "http://rok3.me/"
languageCode = "en-us"
title = "Rob's Programming Adventures"
theme = "hugo-future-imperfect"
staticDir = "static"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Rob's programming adventures."
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Robert Kaufmann III"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true

    viewMorePostLink     = "/blog/"

    categoriesByCount    = true
    includeReadingTime   = true

[params.intro]
    header    = "Robert Kaufmann III"
    paragraph = "Software Engineer. Cyclist. Photographer. Ninja."
    about     = ""

[params.intro.pic]
    src       = "/img/profile.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "Hugo Future Imperfect"

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Programming"
    url = "/categories/programming/"
    identifier = "fa fa-code"
    weight = 2

[[menu.main]]
    name = "Electronics"
    url = "/categories/electronics/"
    identifier = "fa fa-bolt"
    weight = 3

[[menu.main]]
    name = "Photography"
    url = "/photography/"
    identifier = "fa fa-camera"
    weight = 4

[[menu.main]]
    name = "About Rob"
    url = "/about/"
    identifier = "fa fa-user"
    weight = 5

[social]
    github          = "robottokauf3"
    twitter         = "rok3"
    linkedin        = "robkaufmann"
    # jsfiddle        = ""
    # codepen         = ""
    # foursquare      = ""
    # dribbble        = ""
    # deviantart      = ""
    # behance         = ""
    # flickr          = ""
    # instagram       = ""
    # youtube         = ""
    # vimeo           = ""
    # vine            = ""
    # medium          = ""
    # wordpress       = ""
    # tumblr          = ""
    # xing            = ""
    # slideshare      = ""
    # stackoverflow   = ""
    # reddit          = ""
    # pinterest       = ""
    # googleplus      = ""
    # facebook        = ""
    # facebook_admin  = ""
    # twitter_domain  = ""
    # email           = ""